### ISSUE TITLE
Gmail doesn't show options(Yes/No/Maybe)

### ISSUE THREAD

**Issue by sergey-morenets** [mangstadt/biweekly#102]
Hi

I recently started using this library and everything works fine except one minor issue.

1. I generated and attached invite.ics to Google email using biweekly.
2. After email was sent I open it in Gmail and I don't see buttons "Yes", "No" and "Maybe". Instead of these buttons I see "Add to calendar" link. That's strange because usual invitations from other people are displayed with these buttons.

I even don't know which properties/flags in iCalendar format are related to this functionality.
Can you please help?

**Comment by mangstadt** [comment]
Maybe try setting the ACTION property to NEEDS_ACTION?

**Comment by sergey-morenets** [comment]
> 
> 
> Maybe try setting the ACTION property to NEEDS_ACTION?

Hi
Thank you for quick response.
I also tried to set this property but nothing has changed.
Here is extract from generated .ics file:

STATUS:CONFIRMED
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=sergey:mailto:mail@mail.com

**Comment by mangstadt** [comment]
Try setting RSVP=TRUE?

ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CN=sergey:mailto:mail@mail.com

**Comment by sergey-morenets** [comment]
> 
> 
> Try setting RSVP=TRUE?
> 
> ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;PARTSTAT=NEEDS-ACTION;CN=sergey:mailto:[mail@mail.com](mailto:mail@mail.com)

Thank you for the hint. I added "RSVP=TRUE" to the attendee but it didn't help.

**Comment by mangstadt** [comment]
Try adding a STATUS property to the VEVENT?

BEGIN:VEVENT
STATUS:NEEDS-ACTION
...
END:VEVENT

Also, this might help? https://github.com/icalendar/icalendar/issues/103

**Comment by sergey-morenets** [comment]
> 
> 
> Try adding a STATUS property to the VEVENT?
> 
> BEGIN:VEVENT
> STATUS:NEEDS-ACTION
> ...
> END:VEVENT
> 
> Also, this might help? [icalendar/icalendar#103](https://github.com/icalendar/icalendar/issues/103)

Hi

I finally figured out how to show this Yes/No/Maybe buttons. There's a special property METHOD in the body so I needed to change it to REQUEST:
METHOD:REQUEST

**Comment by mangstadt** [comment]
Great!

**Comment by chai2** [comment]
@sergey-morenets - Glad you figured. I'm having a similar issue - mind sharing the snippet that shows how to set `METHOD:REQUEST` as part of the body?
