### ISSUE TITLE
GraalVM Native Image compatibility

### ISSUE THREAD

**Issue by Hixon10** [mangstadt/biweekly#104]
Hello!
Thank you for such amazing library.
 
I wanted to try your library with <a href="GraalVM Native Image">https://www.graalvm.org/reference-manual/native-image/</a>. However, it does not work out the box. GraalVM is too young project, so it is OK. 

So, I understand, that your library does not have any problems, and it is about bugs in GraalVM. However, if you would like to support this platform, you may to fix 2 places:

1. We got `NPE` in this block of code:
```
	static {
		InputStream in = null;
		try {
			in = Biweekly.class.getResourceAsStream("biweekly.properties");
			Properties props = new Properties();
			props.load(in);
	}
///
}
```

The reason is graalvm cannot load `Biweekly.class.getResourceAsStream("biweekly.properties")`. 

2. We got `ClassNotFoundException` because of this code:
```
	private final transient ResourceBundle messages;

	Messages() {
		messages = ResourceBundle.getBundle("biweekly/messages");
	}
```

So, it is about resources in both cases. When I locally fixed it, `biweekly` perfectly started, as part of Native image.

**Comment by mangstadt** [comment]
Hi, thanks for posting!

How did you fix it? Maybe I can add the fix to biweekly.

**Comment by Hixon10** [comment]
I did a dirty hacks :) 

For `in = Biweekly.class.getResourceAsStream("biweekly.properties");` I just inlined needed settings. 

For `Messages` I created a class, which contains all `biweekly/messages` values. 

But If you have vision, how these problems may be fixed, I can implement it and create a PR.

**Comment by mangstadt** [comment]
I am glad that solution worked for you, but I'd rather not move all that stuff into the code. :)

- **biweekly.properties:** This file is there so that Maven can edit certain information at build time without modifying the code.
- **messages.properties:** I'd like to keep the messages in this file for organizational reasons.

The fact that GraalVM can't read files from the classpath seems like a major deficiency to me. It is not uncommon for Java code to do that. 😕

**Comment by Hixon10** [comment]
Yeah, I totally agree with you. I will try to contact with someone connected with GraalVM. Maybe, I did something wrong, or I need to use some flags for `native-image` tool.
