### ISSUE TITLE
Organizer's email not recognized in Apple ICS 

### ISSUE THREAD

**Issue by golszewski86** [mangstadt/biweekly#113]
Apple iCloud calendar returns event organizer in the following format:

```
ORGANIZER;CN=Organizer Name;EMAIL=organizer.test@icloud.com:/aMTc4MjA5ODM
 wMDQxNzgyMFOz1I9CYraecqqxCBpAcPRegJ6OKuR39614Y6GLCrXV/principal/
```
And biweekly (version 0.6.6.) parses it to the following Organizer object:

```
biweekly.property.Organizer [ parameters={EMAIL=[organizer.test@icloud.com]} | name=Organizer Name | email=null | uri=/aMTc4MjA5ODMwMDQxNzgyMFOz1I9CYraecqqxCBpAcPRegJ6OKuR39614Y6GLCrXV/principal/ ]
```

As you can see, the `email` is `null` and the actual email address is available as extra `EMAIL` parameter.

**Comment by golszewski86** [comment]
And I think the fix would be pretty easy because in the `biweekly.io.scribe.property.OrganizerScribe._parseText(String, ICalDataType, ICalParameters, ParseContext)` method parameters contain email so it could be something like:

```
email = parameters.get("email");
```

**Comment by mangstadt** [comment]
The `Organizer.email` field is null because the EMAIL parameter in your example is not part of the official RFC specification.

https://datatracker.ietf.org/doc/html/rfc5545#section-3.8.4.3

You can get the value of the EMAIL parameter by calling the `getParameter` method.

```java
VEvent event = ...
String email = event.getOrganizer().getParameter("EMAIL");
```
