### ISSUE TITLE
Could not download TZ info

### ISSUE THREAD

**Issue by motoshira** [mangstadt/biweekly#114]
Hi, and thanks for good library.

The problem occurs when using `download` method in `biweekly.io.TimezoneAssignment`.
https://mangstadt.github.io/biweekly/javadocs/latest/src-html/biweekly/io/TimezoneAssignment.html#line.98

It throws an exception `IllegalArgumentException: Timezone ID not recognized.`

It seems that the GET request to tzurl.org is probably causing a 302 redirect and resulting in an error.

**Comment by theigl** [comment]
Same here. I think the code needs to be changed to either follow redirects or directly use the https URL.

**Comment by CorySavit** [comment]
Maybe helpful.
https://mangstadt.github.io/biweekly/javadocs/latest/src-html/biweekly/io/StreamReader.html#line.178 returns null.
Not sure if that's because the structure returned by tzurl.org has changed, and so the reader stopped working, or what. Just thought it might be helpful.

**Comment by theigl** [comment]
I debugged it, the reader tries to parse the 302 HTML response. That's why the result is null.

The way to fix this is to change the URL protocol to HTTPS.

**Comment by mangstadt** [comment]
I can't reproduce this. Can someone please post a timezone that is failing?

I have tried several timezones and they all work for me. If I change the tzurl.org URL to use HTTPS, it throws a `SSLHandshakeException`.

**Comment by theigl** [comment]
It works again. Maybe tzurl.org fixed their redirects.

It seems timezones are currently hosted under URLs like this: https://static.tzurl.org/zoneinfo/Europe/Vienna.ics.

It might make sense to adjust `TzUrlDotOrgGenerator` to this URL structure, so it doesn't have to follow redirects.

**Comment by mangstadt** [comment]
I'm hesitant to change it because the `TZURL` property in the downloaded .ics file still uses the old URL. This suggests that the site administrators would prefer people to use that one.

`TZURL:http://tzurl.org/zoneinfo/America/New_York`

**Comment by motoshira** [comment]
Sorry for the late reply.
I confirmed it works again.
Thanks!
