### ISSUE TITLE
åäö become ???

### ISSUE THREAD

**Issue by piotrblasiak** [mangstadt/biweekly#118]
Is this a limitation or a bug, and can we work around it?

**Comment by mangstadt** [comment]
It's fine, we don't need those letters anyway.

**Comment by darku77** [comment]
@piotrblasiak 

> Is this a limitation or a bug, and can we work around it?

final ICalendar c = new ICalendar();
....
return Biweekly.write(c).go().getBytes(StandardCharsets.UTF_8);
.... 
//write to file
