### ISSUE TITLE
EXDATE is parsed as a DATE-TIME while it is a DATE

### ISSUE THREAD

**Issue by lucclaes** [mangstadt/biweekly#125]
While parsing a VEVENT with:
EXDATE:20230325
the result is an ICalDate with hasTime == true

while with:
EXDATE;VALUE=DATE:20230325
the result is an ICalDate with hasTime == false, as expected.

Isn't VALUE=DATE optional and shouldn't the first EXDATE parse to a DATE ICalDate ?

**Comment by mangstadt** [comment]
If EXDATE does not have a VALUE parameter, then the default data type will be DATE-TIME. This is why the `ICalDate` object says it has a time component when the original date string does not.

In other words, `EXDATE:20230325` is the same as `EXDATE;VALUE=DATE-TIME:20230325`

**Comment by lucclaes** [comment]
Thank you. I thought a YYYYMMDD format was implicitly interpreted as a VALUE=DATE but, by reading RFC 5545 I was wrong...
