### ISSUE TITLE
Timezone not working if date is in the future and after a daylight saving switch

### ISSUE THREAD

**Issue by InteractiveScape** [mangstadt/biweekly#126]
I have an ics-file of an event in the future after the next daylight saving switch on 29/10/2023.
The event time returned by biweekly is one hour off the actual time because ICalTimeZone.inDaylightTime() erroneously returns true for that date.

This issue looks similar to https://github.com/mangstadt/biweekly/issues/115.

I drilled the issue down to ICalTimeZone.java line 426.
The advanceTo() method does not seem to work and the subsequent `it.hasNext()` on line 431 returns false.

If I remove the call to advanceTo() and add a naive `if (cur.compareTo(last) <= 0) continue;` after `cur = it.next();`. This change unnecessarily iterates over all dates again, but missing dates are properly added to the DateCache and `getObservanceDateClosestToTheGivenDate` now returns a correct date instead of null.

This is a minimal ics file to reproduce the issue:
BEGIN:VCALENDAR
VERSION:2.0
PRODID:Microsoft Exchange Server 2010
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=W. Europe Standard Time:20231122T093000
DTEND;TZID=W. Europe Standard Time:20231122T120000
END:VEVENT
END:VCALENDAR

**Comment by mangstadt** [comment]
The fix you described doesn't work for me. Is this what you did?

```java
if ((after && comparison <= 0) || comparison < 0) {
	RecurrenceIterator it = createIterator(observance);

	/*
	 * The "advanceTo()" method skips all dates that are less than the
	 * given date. I would have thought that we would have to call
	 * "next()" once because we want it to skip the date that is equal
	 * to the "last" date. But this causes all the unit tests to fail,
	 * so I guess not.
	 */
	//it.advanceTo(last); //REMOVED
	//it.next();

	DateValue prev = null, cur = null;
	boolean stopped = false;
	while (it.hasNext()) {
		cur = it.next();
		if (cur.compareTo(last) <= 0) continue; //ADDED
		dateCache.add(cur);

		if (givenDate.compareTo(cur) < 0) {
			//stop if we have passed the givenTime
			stopped = true;
			break;
		}

		prev = cur;
	}
	return after ? (stopped ? cur : null) : prev;
}
```

**Comment by InteractiveScape** [comment]
I just realized that in my production code I used `if (cur.compareTo(last) < 0) continue;` without the =.
However that would add a duplicate to the cache when `cur.compareTo(last) == 0`. That's why I added the = without further testing however the breaking condition afterwards is important.

That's my current working version:
```
DateValue prev = null, cur = null;
boolean stopped = false;
while (it.hasNext()) {
    cur = it.next();
    int curComparison = cur.compareTo(last);
    if (curComparison < 0) continue;

    if (curComparison > 0) {
        dateCache.add(cur);
    }
				
    if (givenDate.compareTo(cur) < 0) {
        //stop if we have passed the givenTime
        stopped = true;
        break;
    }

    prev = cur;
}
return after ? (stopped ? cur : null) : prev;
```

**Comment by mangstadt** [comment]
I keep getting 8:30 for the start time instead of 9:30. Do you see anything wrong with this unit test?

```java
@Test
public void test() throws Exception {
	ICalendar ical = Biweekly.parse(getClass().getResourceAsStream("issue126.ics")).first();
	VEvent event = ical.getEvents().get(0);

	/*
	 * The event dates come after the last Sunday in October, so they should
	 * be in standard time (offset of +01:00).
	 */

	Date expected = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss Z").parse("2023-11-22 09:30:00 +0100");
	Date actual = event.getDateStart().getValue();
	assertEquals(expected, actual); //FAILS -- the time is 8:30, not 9:30

	expected = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss Z").parse("2023-11-22 12:00:00 +0100");
	actual = event.getDateEnd().getValue();
	assertEquals(expected, actual);
}
```

**Comment by InteractiveScape** [comment]
No, the unit test looks good and works for me together with my above changes to ICalTimeZone.

**Comment by M66B** [comment]
The same problem occurs in this ics file:

```
BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:GMT Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T010000
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN=OrganiserName
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=rcpt
DESCRIPTION;LANGUAGE=en-GB:BLAHBLAHBLAH
UID:xxxxxxxxxxxxxx
 xxxxxxxxxx
SUMMARY;LANGUAGE=en-GB:Meeting Title
DTSTART;TZID=GMT:20231030T103000
DTEND;TZID=GMT:20231030T110000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20231027T114207Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-GB:Microsoft Teams Meeting
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:xxxxxx
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-ONLINEMEETINGINFORMATION:xxxxxxx
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
X-MICROSOFT-REQUESTEDATTENDANCEMODE:DEFAULT
X-MICROSOFT-LOCATIONDISPLAYNAME:Microsoft Teams Meeting
X-MICROSOFT-LOCATIONSOURCE:None
X-MICROSOFT-LOCATIONS:[{"DisplayName":"Microsoft Teams Meeting"\,"LocationA
 nnotation":""\,"LocationUri":""\,"LocationStreet":""\,"LocationCity":""\,"
 LocationState":""\,"LocationCountry":""\,"LocationPostalCode":""\,"Locatio
 nFullAddress":""}]
BEGIN:VALARM
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by M66B** [comment]
Applying this patch resolves the issue:

https://github.com/mangstadt/biweekly/issues/126#issuecomment-1774668870

**Comment by mangstadt** [comment]
@M66B Your example cannot be used to test this issue. The start/end dates of the event do not make use of the VTIMEZONE definition. Their TZID parameter is set to "GMT", which does not match the TZID value of the VTIMEZONE definition.

**Comment by M66B** [comment]
Still, the proposed changes result in a correct even start and end time.

**Comment by mangstadt** [comment]
My unit test is working now. I might have forgotten to remove the `it.advanceTo()` line.

Patch has been merged. Thanks for your work @InteractiveScape!
