### ISSUE TITLE
Provide a way to cancel an existing events

### ISSUE THREAD

**Issue by tadchristiansen** [mangstadt/biweekly#15]
I have been searching through the documentation and don't see any way to create an ics file that cancels an existing event. I have just started using this library and it is fantastic. Just wanted to add event cancellations to the wish list :).

**Comment by mangstadt** [comment]
Hi tad,

I came across an [SO answer](http://stackoverflow.com/a/10561761/13379) that addresses this.  Also see [this thread on Sourceforge](https://sourceforge.net/p/dday-ical/discussion/656447/thread/6f35e5d9) (it's for a .NET iCalendar library, but that doesn't matter).

To cancel an existing event, try creating a new ics file that contains a VEVENT with the following properties:

* STATUS: Set this to "cancelled".
* UID: Set this to the same UID as the existing event.
* SEQUENCE: Set this to a value that is larger than the SEQUENCE property of the existing event.  If the existing event didn't have a SEQUENCE value, "2" should do.

```java
ICalendar ical = new ICalendar();
VEvent event = new VEvent();
event.setStatus(Status.cancelled());
event.setUid(...);
event.setSequence(2);
ical.addEvent(event);
```

Please let me know if it works!

-Mike

**Comment by tadchristiansen** [comment]
I will give that a shot in the next few days. Right now I am implementing our invites and plan on doing the cancels soon. I will let you know how it goes. I didn't want to log an issue for this one: http://stackoverflow.com/questions/33967246/add-multiple-events-to-ical-with-biweekly because I don't think its an issue with your code. Check out the question if you have time.

**Comment by mangstadt** [comment]
Hi @tadchristiansen,

I was wondering if you could provide an update on whether you were able to successfully cancel an event.  If so, how did you do it?  Thank you.

**Comment by mangstadt** [comment]
Assuming issue was resolved.  Closing.
