### ISSUE TITLE
Attendee/Organizer emails not discovered with upper case MAILTO

### ISSUE THREAD

**Issue by mcantrell** [mangstadt/biweekly#17]
Outlook.com produces ics files with MAILTO URIs:

    ATTENDEE;CUTYPE=INDIVIDUAL;CN=John Doe;ROLE=REQ-PARTICIPAN
     T;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:MAILTO:jdoe@acme.com
    ORGANIZER;CN=John Smith:MAILTO:jsmith@acme.com

The biweekly API returns null for the email on the attendee/organizer. If you lower-case the URI, it works as expected:

    ATTENDEE;CUTYPE=INDIVIDUAL;CN=John Doe;ROLE=REQ-PARTICIPAN
     T;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:jdoe@acme.com
    ORGANIZER;CN=John Smith:mailto:jsmith@acme.com

Is case sensitivity required? The specs I've seen usually document them as upper case. In practice, most clients seem to use lower case (except outlook.com). 

Test Case  (groovy):

    @Test
    void testOutlookCalendar() {
        def ical = Biweekly.parse(new FileInputStream("test-outlook.ics")).first()
        assertEquals("jdoe@acme.com", ical.events.first().attendees.first().email)
        assertEquals("jsmith@acme.com", ical.events.first().organizer.email)
    }

See attached file: [test-outlook.ics.zip](https://github.com/mangstadt/biweekly/files/75018/test-outlook.ics.zip)

**Comment by mangstadt** [comment]
Mike,

Thanks for the report.  If Outlook does it this way, I guess I have no choice, do I? ;)

**Comment by mangstadt** [comment]
Fixed in 8009144ebffa696b25fc038115df554127099f46.
