### ISSUE TITLE
mybatis example

### ISSUE THREAD

**Issue by patrek** [mangstadt/biweekly#26]
Not sure if this is the right channel. If not, please indicate which channel to use.

Any example on how to use biweekly with mybatis? Working on an application where biweekly VEvent need to be store in a database.

Thanks.

**Comment by mangstadt** [comment]
Hi Patrick,

That is a very broad question.  You probably won't get much help no matter where you post it to.

I can't help you with mybatis, but if you have any questions related to biweekly specifically, please let me know.

Thank you,
Mike
