### ISSUE TITLE
Support JDK 8 for compile

### ISSUE THREAD

**Issue by brunojcm** [mangstadt/biweekly#42]
The project cannot be compiled using JDK 8 because of some javadoc generation problems, as explained here:

http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by mangstadt** [comment]
Bruno,

Thank you for reporting this.  Fixed in 8e7cf056f0d776a7fe3f634470658d003571b3ce.

Thank you,
Mike
