### ISSUE TITLE
DateIterator.advanceTo fails to advance under certain conditions

### ISSUE THREAD

**Issue by drtobster** [mangstadt/biweekly#49]
In the course of using the `advanceTo` method on a `DateIterator` I have come across an issue that exists in release 0.4.6 whereby the `advanceTo` method on an `DateIterator` fails to actually advance. 

This unit test below illustrates the problem. In the unit test, a `Recurrence` is created with a `DAILY` frequency, a start time of `2016-07-01 00:01:00`, and a time zone of `America/Los_Angeles`. After fetching the iterator it is advanced to `2016-07-01 06:59:00` then `next` is called on the iterator. The first occurrence, which is the start time, should be skipped but it is not.

```
@Test
	public void advanceIterator() {

		// Use time zone with negative offset
		TimeZone pacificTimeZone = TimeZone.getTimeZone("America/Los_Angeles");
		Date startTime = date("2016-07-01 00:01:00", pacificTimeZone);
		Date advanceTo = date("2016-07-01 06:59:00", pacificTimeZone); // advance iterator to the time that is 1-minute less than the time zone offset.

		// Note: date-time used for advancement must first be converted to UTC first.
		Recurrence recur = new Recurrence.Builder(Recurrence.Frequency.DAILY).count(4).build();
		RecurrenceProperty recurrenceProperty = new RecurrenceProperty(recur);
		DateIterator it = recurrenceProperty.getDateIterator(startTime, pacificTimeZone);
		it.advanceTo(new Date(advanceTo.getTime())); //

		//@formatter:off
		// First occurrence is skipped. The last three occurrences should be returned.
		List<Date> expected = Arrays.asList(
				date("2016-07-02 00:01:00", pacificTimeZone),
				date("2016-07-03 00:01:00", pacificTimeZone),
				date("2016-07-04 00:01:00", pacificTimeZone)
		);
		//@formatter:on

		List<Date> actual = new ArrayList<Date>();
		while (it.hasNext()) {
			actual.add(it.next());
		}

		assertEquals(expected, actual);
	}
```

The root cause of the problem appears to be method `convert` in `TimeUtils.java`: https://github.com/mangstadt/biweekly/blob/master/src/main/java/biweekly/util/com/google/ical/util/TimeUtils.java#L88-89

When converting *from* UTC within method `convert`, line 89 where method `addSeconds` is called, is not necessary. The UTC time passed into the method has already been adjusted to the time zone passed into `convert` by line 88. Because `addSeconds` is called, the `DateTimeValue` returned in line 88 is further adjusted by the offset of the time zone in use. For the unit test above, the `DateTimeValue` returned by line 88 is `2016-07-01 06:59:00`. The call to `addSeconds` causes -25,200 seconds (e.g. -7 hours) to be added which adjusts the value (back) further to `2016-06-30 23:59:00`. Note this is actually *prior* to the start time. Because the iterator is now behind the the start-time, the first call to `next` causes the occurrence at the start-time to be returned.

It should be noted that this problem arose due to PR #39, which I submitted. That PR resolved an issue related to the DST gap hour but apparently created the issue reported here. The problem described by this issue does not exist in releases prior to 0.4.6, though the issue resolved by PR #39 would exist.

I am working on a fix for this issue and associated unit tests. A PR will be submitted for your review today or tomorrow.

**Comment by drtobster** [comment]
@mangstadt, do you have a date for the next release of BiWeekly? I ask as the fix just merged is very much needed by a scheduling web service here at Cisco that relies on BiWeekly. That service, while internal to Cisco, does support aspects of the Cisco Spark product that is in production. If no release is coming soon I'll need to figure out a workaround.

**Comment by mangstadt** [comment]
@drtobster I'll see if I can publish a new version in the next couple days.  I'm working on a big change that cleans up the way timezones are handled, so I don't want to rush it.

**Comment by mangstadt** [comment]
I may have time to publish a release tomorrow.  Will let you know.

**Comment by mangstadt** [comment]
@drtobster It's released!

**Comment by drtobster** [comment]
Awesome! Thank-you very much.
