### ISSUE TITLE
ICalendar to Android Intent

### ISSUE THREAD

**Issue by LucioC** [mangstadt/biweekly#52]
Hello,

I'm starting to use the biweekly library, and I want to use the parsed iCalendar data to create an intent that will prompt the user to add the event to its calendar app.

Is there any easy way to do that?
I'm having to get each value and fill the intent specific parameter.

I'm stuck on the RRULE. I think I need to pass a single RAW String to the RRULE android field, like: "FREQ=WEEKLY;COUNT=9;BYDAY=WE,FR"

When I parse the event I can't find a way to get this raw parameter string that was included in the icalendar data. How can I do that without the need to reconstruct the string using each separated parameter value?

**Comment by mangstadt** [comment]
Hi Lucio,

You can use `RecurrenceRuleScribe` to convert a `RecurrenceRule` object into a string:

```java
VEvent event = ...
RecurrenceRule rrule = event.getRecurrenceRule();

RecurrenceRuleScribe scribe = new RecurrenceRuleScribe();
WriteContext context = new WriteContext(ICalVersion.V2_0, new TimezoneInfo(), null);
String string = scribe.writeText(rrule, context);
```

Does this help?

**Comment by LucioC** [comment]
yes, that works great
thanks!
