### ISSUE TITLE
mvn package fails due to testrun

### ISSUE THREAD

**Issue by mfernau** [mangstadt/biweekly#54]
I can't build JAR-Package because the testrun fails:
```
Results :

Failed tests:
  Google2445UtilsTest.getDateIterator:124->assertIteratorEquals:132 expected:<Sun Mar 27 20:00:00 CEST 2016> but was:<Sun Mar 27 15:00:00 CEST 2016>

Tests run: 1036, Failures: 1, Errors: 0, Skipped: 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.862s
[INFO] Finished at: Tue Aug 23 10:33:13 CEST 2016
[INFO] Final Memory: 32M/457M
[INFO] ------------------------------------------------------------------------
```

**Comment by mangstadt** [comment]
Thanks for the report.  I'll look into it.

**Comment by mangstadt** [comment]
@mfernau What timezone do you live in?  I would like to try to reproduce it on my computer.  Thank you.

**Comment by mfernau** [comment]
Hi, I'm living in germany. Timezone is cest. 
Thanks for looking into it.
Martin

Am 11. September 2016 00:19:26 MESZ, schrieb Mike Angstadt <notifications@github.com>:
>@mfernau What timezone do you live in?  I would like to try to
>reproduce it on my computer.  Thank you.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mangstadt/biweekly/issues/54#issuecomment-246147252

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mangstadt** [comment]
My guess is that there is a daylight savings time boundary around that time for the CET timezone.  I changed the unit test to use a specific timezone in 3afccfeb3369451d1f6384f4e99efbb8cdd92883.  Please let me know if you can build it now.

**Comment by mfernau** [comment]
Great, now all works as expected. mvn "compile" "test" and "package" are all going through without any errors.
Thanks!

**Comment by mangstadt** [comment]
No problem!
