### ISSUE TITLE
Question: Does this API provide the capability to monitor mailbox for calendar activity

### ISSUE THREAD

**Issue by lekkalapudi** [mangstadt/biweekly#55]
This is a basic question. Unfortunately i couldn't get the required details any where. Does this API provide me the capability to monitor the mailbox for acceptance status of attendees pertaining to calendar invites?

**Comment by mangstadt** [comment]
No, sorry.  This library simply parses iCalendar files.

**Comment by chaithanyabi** [comment]
Thanks a lot for quick response :).
