### ISSUE TITLE
EnumProperty could be Enums

### ISSUE THREAD

**Issue by philipwhiuk** [mangstadt/biweekly#56]
I'm curious why EnumProperty classes like Method aren't Java enums.

It would seem to make it much easier to parse them.

Even not being enums, one can't even do:

switch(method.getValue()) {
    case Method.PUBLISH:
}

because Method.PUBLISH is private.

**Comment by mangstadt** [comment]
They're not enums because it's possible to assign any value to a property (for example, `METHOD:FOOBAR`).

Good point about the string constants being private.  I made them public in xxx.
