### ISSUE TITLE
How convert Android event recurrence params into Biweekly objects? 

### ISSUE THREAD

**Issue by yamelkaya** [mangstadt/biweekly#57]
Hi @mangstadt, I am new in your library and I'd like to sorry in advance if the question is trivial. I want to select android events and convert them into `VEvent` for future processing. I am stuck with converting from string and setting following fields:

```
CalendarContract.Events.RRULE (String),
CalendarContract.Events.RDATE (String), 
CalendarContract.Events.EXDATE (String), 
CalendarContract.Events.EXRULE (String)
```

I need probably these methods from your library 

```
setRecurrenceRule();
addRecurrenceDates();
addExceptionRule();
addExceptionDates();
```

but I haven't found how to parse their parameters from string. How can I do that with your library? 

Thanks for your library and I highly appreciate your help.

**Comment by yamelkaya** [comment]
Probably I found the answer. I need `RecurrenceRuleScribe` and `RecurrenceDatesScribe` (with `ICalVersion.V1_0`).

**Comment by mangstadt** [comment]
Glad you found the answer.  Let me know if you need any more help.
