### ISSUE TITLE
DaySaveTime issue

### ISSUE THREAD

**Issue by yuanl2** [mangstadt/biweekly#61]
Hi mangstadt
I used the biweekly(version 0.6.0) to generate executed times. But if the date value equals 
' Sun Nov 06 01:46:46 PST 2016'    or  ' Sun Nov 06 01:46:46 PDT 2016'
the result is same. I am not sure that is correct.  
If there is no problem, pls ignore this issue.

The code:
`  final TimeZone pacificTimeZone = TimeZone.getTimeZone("America/Los_Angeles");

Recurrence.Builder builder = new Recurrence.Builder(Frequency.DAILY);
        builder.count(5);
        builder.interval(1);
        RecurrenceIterator recurrenceIterator = RecurrenceIteratorFactory.createRecurrenceIterator(builder.build(), date, pacificTimeZone);
        DateIterator dateIterator = DateIteratorFactory.createDateIterator(recurrenceIterator);
        while (dateIterator.hasNext()) {
            System.out.println(dateIterator.next());
        }`

date = 'Sun Nov 06 01:46:46 PDT 2016'
Output
Sun Nov 06 01:46:46 PST 2016
Mon Nov 07 01:46:46 PST 2016
Tue Nov 08 01:46:46 PST 2016
Wed Nov 09 01:46:46 PST 2016
Thu Nov 10 01:46:46 PST 2016
----------------------------------------
date = 'Sun Nov 06 01:46:46 PST 2016'
Output
Sun Nov 06 01:46:46 PST 2016
Mon Nov 07 01:46:46 PST 2016
Tue Nov 08 01:46:46 PST 2016
Wed Nov 09 01:46:46 PST 2016
Thu Nov 10 01:46:46 PST 2016

**Comment by mangstadt** [comment]
Can you please provide a complete code sample?  The "date" variable is not defined.

**Comment by yuanl2** [comment]
package test.my;

import biweekly.util.Frequency;
import biweekly.util.Recurrence;
import biweekly.util.com.google.ical.compat.javautil.DateIterator;
import biweekly.util.com.google.ical.compat.javautil.DateIteratorFactory;
import biweekly.util.com.google.ical.iter.RecurrenceIterator;
import biweekly.util.com.google.ical.iter.RecurrenceIteratorFactory;
import biweekly.util.com.google.ical.values.DateTimeValue;
import biweekly.util.com.google.ical.values.DateTimeValueImpl;

import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.TimeZone;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
        ZoneId pacificTimeZoneId = ZoneId.of("America/Los_Angeles");
        Instant now = Instant.now().minus(Duration.ofMinutes(5));
        DateTimeValue date = getDateTimeValueFromInstant(now, pacificTimeZoneId);
        final TimeZone pacificTimeZone = TimeZone.getTimeZone("America/Los_Angeles");

        System.out.println("###############------  pacificTimeZone  startTime = " +  new Date(now.toEpochMilli()) );

        Recurrence.Builder builder = new Recurrence.Builder(Frequency.DAILY);
        builder.interval(1);
        builder.count(5);

        RecurrenceIterator recurrenceIterator = RecurrenceIteratorFactory.createRecurrenceIterator(builder.build(), date, pacificTimeZone);
        DateIterator dateIterator = DateIteratorFactory.createDateIterator(recurrenceIterator);
        while (dateIterator.hasNext()) {
            System.out.println(dateIterator.next());
        }
    }

    private static DateTimeValue getDateTimeValueFromZonedDateTime(final ZonedDateTime zonedDateTime) {

        return new DateTimeValueImpl(
                zonedDateTime.getYear(),
                zonedDateTime.getMonthValue(),
                zonedDateTime.getDayOfMonth(),
                zonedDateTime.getHour(),
                zonedDateTime.getMinute(),
                zonedDateTime.getSecond());
    }

    private static DateTimeValue getDateTimeValueFromInstant(final Instant instant, ZoneId id) {

        ZonedDateTime zonedDateTime = ZonedDateTime.ofInstant(instant, id);
        return getDateTimeValueFromZonedDateTime(zonedDateTime);
    }
}

I  set my time as 'Sun Nov 06 01:46:46 PST 2016' and 'Sun Nov 06 01:46:46 PDT 2016'.
And set my timezone as 'America/Los_Angeles'

I think the class DateTimeValueImpl can't distinguish the 'Sun Nov 06 01:46:46 PST 2016' and 'Sun Nov 06 01:46:46 PDT 2016'. Right?
Thank you.
