### ISSUE TITLE
Cannot selectively ignore parse warnings

### ISSUE THREAD

**Issue by carolinelane10** [mangstadt/biweekly#64]
I want to be able to parse ICalendar's that use global ID's for timezones rather than a VTIMEZONE component. Whenever I try to parse an ICalendar that is formatted this way, I get this warning: (37): No VTIMEZONE component exists. ID will be treated as an Olsen timezone ID instead. Which is fine. Except that the ParseWarnings object just stores a list of error messages as Strings with no mapping to the error code, so I have to do something like this to ignore the warning:

```
reader.getWarnings().forEach(warning -> {
          if (!warning.startsWith("(37)")) {
            errorResponse.addMessage(warning);
          }
        });
```

I don't think this is a good way to do this at all, especially because I have seen parse warnings that start with the line number rather than the error code.

**Comment by mangstadt** [comment]
Hmm, that would be a good thing to have.  I will work on it.

Regarding the specific warning you are getting: If you want to use global timezone IDs instead of VTIMEZONE components, the proper way to do that is to prefix the TZID parameter value with a forward slash, like so:

```
DTSTART;TZID=/America/New_York:20160109T180000
```

**Comment by carolinelane10** [comment]
Yes, I'm creating it that way, but I still get the warning "(37): No VTIMEZONE component exists. ID will be treated as an Olsen timezone ID instead."

**Comment by mangstadt** [comment]
Can you post a code sample?

**Comment by carolinelane10** [comment]
```
String calendarContent = "["vcalendar",
    [],
    [
        ["vevent",
        [
         
            ["categories",{},"text","4582ee4c-4c1f-453f-ba45-5367d7f6cd8b"],
            ["attendee",{"raw_person_id":"12345","actor_id": "6", "cn":"Superuser Admin", "is_student": true},"cal-address","mailto:testsenderemail@civitaslearning.com"],
            ["dtstart",{"tzid": "America/Chicago"},"date-time","2016-12-05T12:00:00"],
            ["dtend",{"tzid": "America/New_York"},"date-time","2016-12-05T14:00:00"]],
            []
        ]
    ]
]"
try {
      JCalReader reader = new JCalReader(calendarContent);
      ICalendar ical = reader.readNext();
      if (!reader.getWarnings().isEmpty()) {
        ErrorResponse errorResponse = new ErrorResponse(HttpStatus.BAD_REQUEST);
        reader.getWarnings().forEach(warning -> {
          if (!warning.startsWith("(37)")) {
            errorResponse.add(warning);
          }
        });
        if (errorResponse.hasErrors()) {
          // return 400 response
        }
      } catch (IOException e) { // return 400 response }
```

**Comment by mangstadt** [comment]
The TZID parameter values do not begin with a forward slash character.  That's why you're getting the warning.  For example:

```
["dtstart",{"tzid": "America/Chicago"},"date-time","2016-12-05T12:00:00"],
```

should be

```
["dtstart",{"tzid": "/America/Chicago"},"date-time","2016-12-05T12:00:00"],
```

**Comment by carolinelane10** [comment]
That worked, thank you! But after parsing, when I do this:
```
System.out.println(ical.getTimezoneInfo().getTimezone(ical.getEvents().get(0).getDateStart()).getTimeZone().getID());
```
I get "America/New_York" (no leading forward slash) and when I write the ical back out like this:
```
String jcal = Biweekly.writeJson(ical).go();
```
 I get this:
```
["dtstart", {"tzid": "America/Chicago"}, "date-time", "2017-01-27T13:00:00" ],
```
Again, no leading forward slash. I couldn't write out a JSON and reparse it without changing it. The TZID's in the [Olsen Database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) don't have a forward slash, so why is it needed in this case?

**Comment by carolinelane10** [comment]
Playing around with it some more, the iCal I was writing to jCal was one I was creating and setting TimezoneAssignments for. It looks like when I create TimezoneAssignments using TimezoneAssignment.download, the result has no leading slash in the jCal and timezoneassignment.getGlobalId() is null (which was why I was using timezoneassignment.getTimezone().getID()), but when I create the TimezoneAssignments using new TimezoneAssignment(timezone, tzid), the resulting jCal has a leading slash and timezoneassignment.getGlobalId() is "America/New_York" which is what I want!

**Comment by mangstadt** [comment]
I wasn't able to reproduce the issue you experienced in your previous comment.  Can you post a complete code sample?

The leading slash has nothing to do with the Olsen Database.  It is part of the iCal syntax when the iCal is **_serialized_**.  That's why you don't get it when you call `TimezoneAssignments.getGlobalID()`.

The leading slash tells the iCal parser that the TZID parameter is a global ID and **_not_** a reference to a VTIMEZONE component.

Does that make sense? :)

**Comment by carolinelane10** [comment]
Thank you, yes your point about global ID vs. reference to VTIMEZONE makes sense!

The code sample is like this:
```
TimezoneAssignment timezoneAssignment = TimezoneAssignment.download(Timezone.getTimezone("America/New_York"), true)
ical.getTimezoneInfo().setTimezone(vevent.getDateStart(), timezoneAssignment);
System.out.println(ical.getTimezoneInfo().getTimezone(vevent.getDateStart()).getGlobalId()
```
is null

**Comment by mangstadt** [comment]
Your code sample doesn't compile.

The `TimezoneAssignment.download()` method creates a timezone assignment that uses a VTIMEZONE component.  So `getGlobalId()` will return null because it is **_not_** using a global ID, it is using a VTIMEZONE component.

The jCal does not have a slash in front of the TZID because the `TimezoneAssignment` is using a VTIMEZONE component, **_not_** a global ID.

**Comment by mangstadt** [comment]
A fix for the warning number issue has been added in a8b1fa6683926339fc29cd7359a1643029d418c8.

Parse warnings are now wrapped in a `ParseWarning` object, which contains the warning code.

**Comment by carolinelane10** [comment]
Thank you!!
