### ISSUE TITLE
Incorrect result if i change the time of only one recurring event from the recurrence series

### ISSUE THREAD

**Issue by Kashif2016** [mangstadt/biweekly#66]
Hi 
 I am using your library to display the all the recurring events. 
Last week i faced a problem that if i change the time of only one recurring event from the recurrence series then it still give me the old timing of meeting instead of the new updated time.
e,g I created 30 recurring meeting from 1 March till 30 March at 14:00 - 15:00,
then later on if i change the time of only one meeting on 5 March at 16:00 - 17:00
then it is giving me the meetings with both old and new times
_Current result:_
3 March ; 14:00 - 15:00
4 March ; 14:00 - 15:00
**5 March ; 14:00 - 15:00
5 March ; 16:00 - 17:00**
.......

_Expected result_
3 March ; 14:00 - 15:00
4 March ; 14:00 - 15:00
**5 March ; 16:00 - 17:00
6 March ; 14:00 - 15:00**

**Comment by mangstadt** [comment]
Hi, thanks for posting.  Can you post a short code sample that demonstrates this issue?

**Comment by Kashif2016** [comment]
Hi , thanks for reply
Please find the attached ICS file at bottom , in case if you need it.
Below is the code which i am using to get all the recurring events in the ics file
`                  
reader = new ICalReader(new File(NAME_OF_FILE));
ical = reader.readNext();
biweekly.component.VEvent event = ical.getEvents().get(0);
DateIterator iterator = event.getDateIterator(TimeZone.getTimeZone(String.valueOf(Locale.US)));                                                        
while (iterator.hasNext()) {
final Date date = iterator.next();
....`

**The Output of the code is** 
`05-Mar-2017
14:00 - 15:00
recurr
                                                                           
05-Mar-2017
16:00 - 17:00
recurr`

[new Calendar recurr.txt](https://github.com/mangstadt/biweekly/files/821500/new.Calendar.recurr.txt)

**Comment by Kashif2016** [comment]
hi @mangstadt 
any update regarding this issue..... ??

**Comment by mangstadt** [comment]
Issue appears to be related to #67.

**Comment by Kashif2016** [comment]
hi @mangstadt
any update regarding this issue..... ??

**Comment by mangstadt** [comment]
The code that you posted does not compile.  Could you please post a complete code sample that demonstrates the issue?
