### ISSUE TITLE
2 test fails in 0.6.1 and master

### ISSUE THREAD

**Issue by Dupplicate** [mangstadt/biweekly#67]
Hi there, I am getting two fails when trying to build the jar:

Running biweekly.util.com.google.ical.iter.RRuleIteratorImplTest
Tests run: 81, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec <<< FAILURE! - in biweekly.util.com.google.ical.iter.RRuleIteratorImplTest
dailyUntilDec4(biweekly.util.com.google.ical.iter.RRuleIteratorImplTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[19971128, 19971129, 19971130, 19971201, 19971202, 19971203, 19971204]> but was:<[19971128, 19971129, 19971130, 19971201, 19971202, 19971203]>
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.run(RRuleIteratorImplTest.java:2384)
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.run(RRuleIteratorImplTest.java:2315)
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.dailyUntilDec4(RRuleIteratorImplTest.java:283)

advanceTo(biweekly.util.com.google.ical.iter.RRuleIteratorImplTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[20000409, 20000718, 20030101, 20030410, 20030719, 20060101, 20060410, 20060719, 20090101]> but was:<[20000409, 20000718, 20030101, 20030410, 20030719, 20060101, 20060410, 20060719]>
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.run(RRuleIteratorImplTest.java:2384)
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.run(RRuleIteratorImplTest.java:2357)
        at biweekly.util.com.google.ical.iter.RRuleIteratorImplTest.advanceTo(RRuleIteratorImplTest.java:1836)

Timezone is CET. JDK is 1.8.0.121

**Comment by carolinelane10** [comment]
I'm having this issue as well. When I create an event that looks like this:
```
["vcalendar",
 [
   ["version", {}, "text", "2.0"]
 ],
 [
   ["vevent",
     [
       ["summary", {}, "text", "Team Meeting"],
       ["description",{},"text","Some things describing this event"],
       ["dtstart", {"tzid": "/America/New_York"}, "date-time", "2017-03-22T12:00:00"],
       ["dtend",{"tzid": "/America/New_York"}, "date-time","2017-03-22T15:00:00"],
       ["rrule", {}, "recur", {"freq":"WEEKLY", "until":"2017-03-29T19:00:00Z", "wkst":"SU", "byday":["WE"]}]
    ],
    []
   ]
 ]
]
```
And I expand the events using the DateIterator:
```
DateIterator dateIterator = vEvent.getDateIterator(eventTimezone);
 while (dateIterator.hasNext()) {
...
}
```
I expect 2 events to be returned, but the second one is not.

**Comment by mangstadt** [comment]
/sigh

Not sure why this is happening.  This might take some time to resolve.

**Comment by mangstadt** [comment]
This issue should be fixed now. See: https://github.com/mangstadt/biweekly/pull/63#issuecomment-697933157
