### ISSUE TITLE
Is possible to set custom ICalDataType?

### ISSUE THREAD

**Issue by MarcoMerlo** [mangstadt/biweekly#70]
Hi @mangstadt 
great library!

I was trying to write "X-ALT-DESC" property to an event but I can't find a way to set the ICalDataType correctly.
I need to write "X-ALT-DESC;FMTTYPE=text/html:all my very bad html goes here" to the ics file but there is no corresponding type.

Is there a way to do that or I need to extend with custom property and scriber?

Thank you in advance

Marco

**Comment by mangstadt** [comment]
Hi @MarcoMerlo.  I'm glad you like biweekly! :grin: 

Simply add a `RawProperty` to your event, like so:

```java
VEvent event = ...
RawProperty property = new RawProperty("X-ALT-DESC", "all my very bad html goes here");
property.addParameter("FMTTYPE", "text/html");
event.addProperty(property);
```

**Comment by MarcoMerlo** [comment]
thank you sooo much!
I'm new to the library, and I didn' think about parameters...

**Comment by mangstadt** [comment]
No problem! :tada:
