### ISSUE TITLE
HTML Formatted Description

### ISSUE THREAD

**Issue by jozuman** [mangstadt/biweekly#71]
I want to add an HTML formatted description to my .ics.

It looks like that would require `X-ALT-DESC;FMTTYPE=text/html:`

I already tried `VEvent.setExperimentalProperty("X-ALT-DESC;FMTTYPE=text/html", value)` and `VEvent.setExperimentalProperty("X-ALT-DESC", value)`. That does not allow me to add the FMTTYPE.

Is there a way to do this today? Is this a feature that can be added?

**Comment by mangstadt** [comment]
```java
VEvent event = ...
String value = ...
RawProperty property = event.setExperimentalProperty("X-ALT-DESC", value);
property.setParameter("FMTTYPE", "text/html");
```

**Comment by jozuman** [comment]
thanks a lot!

**Comment by 3ntropia** [comment]
Have the same problem! Thanks
