### ISSUE TITLE
How to set week start from Sunday when use weekly frequency

### ISSUE THREAD

**Issue by McGar** [mangstadt/biweekly#81]
Hi

Anyone knows to set week start from Sunday when use weekly frequency?

Thanks

**Comment by mangstadt** [comment]
You can call the `workweekStarts()` method when building the `Recurrence` object:

```java
Recurrence recur = new Recurrence.Builder(Frequency.WEEKLY)
  .workweekStarts(DayOfWeek.SUNDAY)
.build()
```
