### ISSUE TITLE
[QUESTION] How to exclude a dependency in a Gradle build

### ISSUE THREAD

**Issue by Skyost** [mangstadt/biweekly#82]
Hey,

First I wanted to say thank you for your library. I like it a lot and I find it better than iCal4j.

Second, I wanted to ask if you can add a little manual on how to exclude a dependency from a Gradle build (as you did for a [Maven build](https://github.com/mangstadt/biweekly/wiki/Dependencies)).

Thank you !

**Comment by mangstadt** [comment]
Thanks!

Not very familiar with Gradle.  Maybe this would help you?

https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991/7
