### ISSUE TITLE
How to create VAlarm based on Android calendar?

### ISSUE THREAD

**Issue by blady214** [mangstadt/biweekly#83]
Hello,

I am trying to use biweekly to create iCal file from Android calendar. I am able fetch fields from providers based on which I can create ICalendar, VEvent and Attendee objecet but I don't know which Android table I should query to create VAlarm object.

There are reminders: https://developer.android.com/reference/android/provider/CalendarContract.RemindersColumns.html and alerts: https://developer.android.com/reference/android/provider/CalendarContract.CalendarAlertsColumns.html in Android but I don't know how to create VAlarm based on this two tables.

Could you explain which fields from above tables I should get to create correspondend VAlarm object?

**Comment by mangstadt** [comment]
Sorry, I don't know anything about Android.
