### ISSUE TITLE
Outlook will not update events. Instead it created duplicates.

### ISSUE THREAD

**Issue by thenninger** [mangstadt/biweekly#87]
I’m having trouble with .ics files and Outlook. I can’t get events to update properly. Outlook always wants to create new events instead of update. The only case where I was able to get a single event to update was to make it a METHOD:REQUEST and give it an ORGANIZER. This however, **does not work** when importing a .ics file with more than one event.

I attached two ics files that work properly when importing to Yahoo and Gmail and Office 365 Outlook app, but they do not work in Outlook desktop application. Import “Entire_Calendar_15.ics” first, then “Entire_Calendar_15_2.ics” – it will create new events instead of update even though all the UIDs are the same.

Also, Outlook opens a .ics file when it has multiple events as a new calendar instead of trying to import it – any suggestions here?

Any help or suggestions are appreciated!

I've tried many old posts like this one. Nothing seems to work completely in Outlook:
https://stackoverflow.com/questions/45453/icalendar-and-event-updates-not-working-in-outlook

[Entire_Calendar_15.zip](https://github.com/mangstadt/biweekly/files/2972681/Entire_Calendar_15.zip)

**Comment by mangstadt** [comment]
Maybe try adding a METHOD property.  I know you have to do this in order to cancel events.

The property goes at the top of your iCal.  I would try giving it a value of PUBLISH.  You can see all available values here: https://tools.ietf.org/html/rfc5546#section-1.4

```java
ICalendar ical = new ICalendar();
ical.setMethod(Method.publish());
```
