### ISSUE TITLE
ORGANIZDR's SENT-BY not handled as per specification

### ISSUE THREAD

**Issue by girishadat** [mangstadt/biweekly#94]
If a participant is sending an update of a meeting invite, on behalf of the organizer, then that participant's email needs to be put as shown below.

ORGANIZER;SENT-BY="mailto:sray@example.com":mailto:jsmith@example.com
(from https://tools.ietf.org/html/rfc5545#section-3.1.18)

Unfortunately,
1. The double quotes and the mailto: are not getting added, if only email is set using Organizer.setSentBy().
2. If we add the escaped double quotes and mailto (like this -> "\\"mailto:participant@domain.com\\""), then it would be rejected with the below IllegalArgumentException.

```
java.lang.IllegalArgumentException: Property "ORGANIZER" has a parameter named "SENT-BY" whose value contains one or more invalid characters.  The following characters are not permitted: [ \n \r " ]
	at com.github.mangstadt.vinnie.io.VObjectWriter.validate(VObjectWriter.java:617)
	at com.github.mangstadt.vinnie.io.VObjectWriter.writeProperty(VObjectWriter.java:465)
	at biweekly.io.text.ICalWriter.writeProperty(ICalWriter.java:327)
	at biweekly.io.text.ICalWriter.writeComponent(ICalWriter.java:250)
	at biweekly.io.text.ICalWriter.writeComponent(ICalWriter.java:266)
	at biweekly.io.text.ICalWriter._write(ICalWriter.java:212)
	at biweekly.io.StreamWriter.write(StreamWriter.java:83)
	at biweekly.io.chain.ChainingTextWriter.go(ChainingTextWriter.java:211)
	at biweekly.io.chain.ChainingTextWriter.go(ChainingTextWriter.java:187)
	at biweekly.io.chain.ChainingTextWriter.go(ChainingTextWriter.java:138)
```

**Comment by girishadat** [comment]
After doing a quick scan through the RFC, it seems the below could also be affected. All require double-quoted mailto: as values.

- ATTENDEE parameters - MEMBER, DELEGATED-TO, DELEGATED-FROm
- ORGANIZER parameter - SENT-BY

**Comment by mangstadt** [comment]
I'm not able to reproduce that. Can you post your code?

If your "sent-by" value does not contain any special characters (like the colon), then it will not enclose the value in double quotes. The double quotes are only required if a parameter value contains special characters.

Here is my test code:

```java
Organizer organizer = new Organizer(null, "jsmith@example.com");
organizer.setSentBy("mailto:sray@example.com");

ICalendar ical = new ICalendar();
VEvent event = new VEvent();
event.setOrganizer(organizer);
ical.addEvent(event);
ical.write(System.out); //produces: ORGANIZER;SENT-BY="mailto:sray@example.com":mailto:jsmith@example.com
```

**Comment by girishadat** [comment]
Thanks a lot, @mangstadt! It works! 

I was trying with just the email id which didn't append the "mailto:" in double-quotes. Then I tried adding both mailto-colon and double-quotes. Never thought the biweekly will add double quotes, seeing the colon, if I add only mailto-colon.

Closing this issue.

**Comment by girishadat** [comment]
Adding this comment for reference by anyone who may face the same problem later.


The INCORRECT way of setting SENT-BY for Organizer:

```java
Organizer organizer = new Organizer(null, "jsmith@example.com");
organizer.setSentBy("sray@example.com");
event.setOrganizer(organizer);
```
The result would be like this: 

> ORGANIZER;SENT-BY=sray@example.com:mailto:jsmith@example.com


The CORRECT way:

```java
Organizer organizer = new Organizer(null, "jsmith@example.com");
organizer.setSentBy("mailto:sray@example.com");
event.setOrganizer(organizer);
```
The result would be like this: 

> ORGANIZER;SENT-BY="mailto:sray@example.com":mailto:jsmith@example.com


(Most probably this could be an issue for the DELEGATED-TO, DELEGATED-FROM, and MEMBER parameters of ATTENDEE as well)

Maybe it would be good to mention this somewhere in the right place in documentation. 
Though this may be a little less intuitive, it is unsafe to change or optimize this behavior as it may impact those who already have this in their code that uses biweekly library.

**Comment by mangstadt** [comment]
The Javadocs for the `setSentBy` method do mention that it _should_ be a mailto URI. I wonder why I didn't make this required—the RFC states that it MUST be a mailto URI.

Javadocs:

`@param uri a URI representing the person (typically, an email URI, e.g "mailto:janedoe@example.com") or null to remove`

From  [RFC5545 p.27](https://tools.ietf.org/html/rfc5545#page-27):

> Description:  This parameter can be specified on properties with a
>       CAL-ADDRESS value type.  The parameter specifies the calendar user
>       that is acting on behalf of the calendar user specified by the
>       property.  **The parameter value MUST be a mailto URI** as defined in
>       [RFC2368].  The individual calendar address parameter values MUST
>       each be specified in a quoted-string.
