### ISSUE TITLE
add sources jar to repository

### ISSUE THREAD

**Issue by sda399** [mangstadt/biweekly#96]
Hi,
By any chance, could you upload sources and javadoc to maven repository? for the latest release maybe?

regards

**Comment by mangstadt** [comment]
They're already there?

https://repo1.maven.org/maven2/com/googlecode/ez-vcard/ez-vcard/0.10.6/

**Comment by sda399** [comment]
ez-vcard?

**Comment by mangstadt** [comment]
Whoops! Sorry, wrong project. Glad you found it.
