### ISSUE TITLE
Event not getting updated/Cancelled in Outlook app, instead creating new event

### ISSUE THREAD

**Issue by sarathvkumar** [mangstadt/biweekly#97]
Created an ICS file and tried saving it in outlook calendar, it was saving without any issue. But if i open that ICS file again, new event is getting generated instead of updating. Same case for CANCEL event also.

But the same ICS file is working fine will all other calendars like ICal, Google Calendar and also in Outlook web.

Problem occurring only in **Outlook app in desktop and mobile.**

Can someone help on this please.

**Sample ICS file content:**
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Michael Angstadt//biweekly 0.6.3//EN
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:20200721T080223Z
SUMMARY:Medical Appointment Summary 
DTSTART:20200721T090223Z
DURATION:PT1H
ORGANIZER:mailto:test@gmail.com
UID:biweekly.property.Uid [ parameters={} | value=1 ]
DESCRIPTION:Test Appointment calendar event
LOCATION:311 Arsenal St  WATERTOWN MA 02472-2782
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

**Comment by mangstadt** [comment]
I don't know if this is what is causing the issue, but it looks like you are setting the UID property value to the string returned by the `Uid.toString()` method.

**Comment by sarathvkumar** [comment]
I tried with constant UID value, even then outlook app is generating new UID in the event getting added to that calendar.

**Comment by sarathvkumar** [comment]
> I don't know if this is what is causing the issue, but it looks like you are setting the UID property value to the string returned by the `Uid.toString()` method.

**Comment by sarathvkumar** [comment]
> I don't know if this is what is causing the issue, but it looks like you are setting the UID property value to the string returned by the `Uid.toString()` method.

I tried with constant UID value, even then outlook app is generating new UID in the event getting added to that calendar.

**Comment by sarathvkumar** [comment]
If possible someone share the ICS file, which is working in the use case i mentioned.
It will be helpful to compare.
