### ISSUE TITLE
Crash in release build (NullPointerException: in == null)

### ISSUE THREAD

**Issue by rt1shnik** [mangstadt/biweekly#98]
I get crash in my release build when try to use `ICalendar`. It works fine on debug build.

```
Caused by java.lang.NullPointerException: in == null
at java.util.Properties.load(Properties.java:246)
at biweekly.Biweekly.<clinit>(Biweekly.java:245)
at biweekly.property.ProductId.biweekly(ProductId.java:72)
at biweekly.ICalendar.<init>(ICalendar.java:173)
```

I think problem here:
```
static {
		InputStream in = null;
		try {
			in = Biweekly.class.getResourceAsStream("biweekly.properties");
			Properties props = new Properties();
			props.load(in);

			VERSION = props.getProperty("version");
			GROUP_ID = props.getProperty("groupId");
			ARTIFACT_ID = props.getProperty("artifactId");
			URL = props.getProperty("url");
		} catch (IOException e) {
			throw new RuntimeException(e);
		} finally {
			IOUtils.closeQuietly(in);
		}
	}
```

I thnk proguard removed `biweekly.properties` file.

**Comment by mangstadt** [comment]
Yes, if the properties file can't be found, then that would cause an NPE to be thrown.

**Comment by rt1shnik** [comment]
@mangstadt Can you help to fix this?

**Comment by mangstadt** [comment]
Someone experienced a similar issue with another project of mine. See this thread:

[https://github.com/mangstadt/ez-vcard/issues/98](https://github.com/mangstadt/ez-vcard/issues/98)

Please let me know if this resolves your issue.

**Comment by rt1shnik** [comment]
@mangstadt 
I've added line below to `proguard-rules.pro` file to fix my issue. But I believe the more elegant and correct way exists to fix this.

```
-keep class biweekly.** { *; }
```

**Comment by mangstadt** [comment]
Thanks so much for sharing your solution!

If you discover a more elegant solution, I would love it if you would post it here, as I'm sure the Proguard/biweekly users would appreciate it. Since a solution was found, I will close this issue. Thanks again!
